version: "3"

services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_API_SELECT_PARQUET: "on"
    command: minio server /data/minio --console-address ":9090"
