service: readql
frameworkVersion: '3'


provider:
  name: aws
  region: eu-west-1
  runtime: python3.11
  logRetentionInDays: 7
  versionFunctions: false

  ecr:
    images:
      readql:
        path: './'

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: 
            - 'arn:aws:s3:::${self:resources.Resources.bucket.Properties.BucketName}/*'
            - 'arn:aws:s3:::${self:resources.Resources.bucket.Properties.BucketName}/*'
          Action: 
            - 's3:GetObject'
            - 's3:PutObject'


functions:
  readql:
    image: readql
    timeout: 10
    memorySize: 256
    events:
      - http:
          method: GET
          path: '/{proxy+}'
          cors: true
    environment:
      READQL_S3_BUCKET_NAME: ${self:resources.Resources.bucket.Properties.BucketName}


resources:
  Resources:
    bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: readql
