name: build

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -vb tests/

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t saaslite

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - image
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: current
          cache: npm
      - run: npx serverless deploy --verbose
